package com.java.model;
// Generated Nov 24, 2016 7:32:38 PM by Hibernate Tools 4.3.1



/**
 * Loaitin generated by hbm2java
 */
public class Loaitin  implements java.io.Serializable {


     private Integer idLoaiTin;
     private String tenLoai;
     private String moTa;

    public Loaitin() {
    }

    public Loaitin(String tenLoai, String moTa) {
       this.tenLoai = tenLoai;
       this.moTa = moTa;
    }
   
    public Integer getIdLoaiTin() {
        return this.idLoaiTin;
    }
    
    public void setIdLoaiTin(Integer idLoaiTin) {
        this.idLoaiTin = idLoaiTin;
    }
    public String getTenLoai() {
        return this.tenLoai;
    }
    
    public void setTenLoai(String tenLoai) {
        this.tenLoai = tenLoai;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }




}


