package com.java.model;
// Generated Nov 24, 2016 7:32:38 PM by Hibernate Tools 4.3.1



/**
 * Quyen generated by hbm2java
 */
public class Quyen  implements java.io.Serializable {


     private Integer idQuyen;
     private String tenQuyen;
     private String moTa;
     private User user;

    public Quyen() {
    }

	
    public Quyen(String tenQuyen, String moTa) {
        this.tenQuyen = tenQuyen;
        this.moTa = moTa;
    }
    public Quyen(String tenQuyen, String moTa, User user) {
       this.tenQuyen = tenQuyen;
       this.moTa = moTa;
       this.user = user;
    }
   
    public Integer getIdQuyen() {
        return this.idQuyen;
    }
    
    public void setIdQuyen(Integer idQuyen) {
        this.idQuyen = idQuyen;
    }
    public String getTenQuyen() {
        return this.tenQuyen;
    }
    
    public void setTenQuyen(String tenQuyen) {
        this.tenQuyen = tenQuyen;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


