package com.java.model;
// Generated Nov 24, 2016 7:32:38 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private Quyen quyen;
     private String userName;
     private String fullName;
     private String passWord;
     private int idquyen;
     private String sdt;
     private String diaChi;
     private String email;
     private boolean gioiTinh;
     private Date birthDay;

    public User() {
    }

	
    public User(Quyen quyen, String userName, String fullName, String passWord, int idquyen, String sdt, String email, boolean gioiTinh) {
        this.quyen = quyen;
        this.userName = userName;
        this.fullName = fullName;
        this.passWord = passWord;
        this.idquyen = idquyen;
        this.sdt = sdt;
        this.email = email;
        this.gioiTinh = gioiTinh;
    }
    public User(Quyen quyen, String userName, String fullName, String passWord, int idquyen, String sdt, String diaChi, String email, boolean gioiTinh, Date birthDay) {
       this.quyen = quyen;
       this.userName = userName;
       this.fullName = fullName;
       this.passWord = passWord;
       this.idquyen = idquyen;
       this.sdt = sdt;
       this.diaChi = diaChi;
       this.email = email;
       this.gioiTinh = gioiTinh;
       this.birthDay = birthDay;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Quyen getQuyen() {
        return this.quyen;
    }
    
    public void setQuyen(Quyen quyen) {
        this.quyen = quyen;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getPassWord() {
        return this.passWord;
    }
    
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }
    public int getIdquyen() {
        return this.idquyen;
    }
    
    public void setIdquyen(int idquyen) {
        this.idquyen = idquyen;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Date getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }




}


