package com.javaweb.model;
// Generated Nov 26, 2016 3:44:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Binhluansanpham generated by hbm2java
 */
public class Binhluansanpham  implements java.io.Serializable {


     private Integer idBinhLuanSanPham;
     private int iduser;
     private int idsanPham;
     private String noiDung;
     private Date dateBinhLuan;

    public Binhluansanpham() {
    }

	
    public Binhluansanpham(int iduser, int idsanPham, String noiDung) {
        this.iduser = iduser;
        this.idsanPham = idsanPham;
        this.noiDung = noiDung;
    }
    public Binhluansanpham(int iduser, int idsanPham, String noiDung, Date dateBinhLuan) {
       this.iduser = iduser;
       this.idsanPham = idsanPham;
       this.noiDung = noiDung;
       this.dateBinhLuan = dateBinhLuan;
    }
   
    public Integer getIdBinhLuanSanPham() {
        return this.idBinhLuanSanPham;
    }
    
    public void setIdBinhLuanSanPham(Integer idBinhLuanSanPham) {
        this.idBinhLuanSanPham = idBinhLuanSanPham;
    }
    public int getIduser() {
        return this.iduser;
    }
    
    public void setIduser(int iduser) {
        this.iduser = iduser;
    }
    public int getIdsanPham() {
        return this.idsanPham;
    }
    
    public void setIdsanPham(int idsanPham) {
        this.idsanPham = idsanPham;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public Date getDateBinhLuan() {
        return this.dateBinhLuan;
    }
    
    public void setDateBinhLuan(Date dateBinhLuan) {
        this.dateBinhLuan = dateBinhLuan;
    }




}


