package com.javaweb.model;
// Generated Nov 28, 2016 3:38:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Binhluantintuc generated by hbm2java
 */
public class Binhluantintuc  implements java.io.Serializable {


     private int idBinhLuanTinTuc;
     private Tintuc tintuc;
     private Users users;
     private String noiDung;
     private Date ngayBinhLuan;

    public Binhluantintuc() {
    }

    public Binhluantintuc(int idBinhLuanTinTuc, Tintuc tintuc, Users users, String noiDung, Date ngayBinhLuan) {
       this.idBinhLuanTinTuc = idBinhLuanTinTuc;
       this.tintuc = tintuc;
       this.users = users;
       this.noiDung = noiDung;
       this.ngayBinhLuan = ngayBinhLuan;
    }
   
    public int getIdBinhLuanTinTuc() {
        return this.idBinhLuanTinTuc;
    }
    
    public void setIdBinhLuanTinTuc(int idBinhLuanTinTuc) {
        this.idBinhLuanTinTuc = idBinhLuanTinTuc;
    }
    public Tintuc getTintuc() {
        return this.tintuc;
    }
    
    public void setTintuc(Tintuc tintuc) {
        this.tintuc = tintuc;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public Date getNgayBinhLuan() {
        return this.ngayBinhLuan;
    }
    
    public void setNgayBinhLuan(Date ngayBinhLuan) {
        this.ngayBinhLuan = ngayBinhLuan;
    }




}


