package com.javaweb.model;
// Generated Nov 26, 2016 3:44:35 PM by Hibernate Tools 4.3.1



/**
 * Chitietdonhang generated by hbm2java
 */
public class Chitietdonhang  implements java.io.Serializable {


     private Integer idchitietdonhang;
     private int iddonhang;
     private double thanhTien;
     private String ghiChu;
     private Integer soLuong;
     private String idSanPham;

    public Chitietdonhang() {
    }

	
    public Chitietdonhang(int iddonhang, double thanhTien, String ghiChu, String idSanPham) {
        this.iddonhang = iddonhang;
        this.thanhTien = thanhTien;
        this.ghiChu = ghiChu;
        this.idSanPham = idSanPham;
    }
    public Chitietdonhang(int iddonhang, double thanhTien, String ghiChu, Integer soLuong, String idSanPham) {
       this.iddonhang = iddonhang;
       this.thanhTien = thanhTien;
       this.ghiChu = ghiChu;
       this.soLuong = soLuong;
       this.idSanPham = idSanPham;
    }
   
    public Integer getIdchitietdonhang() {
        return this.idchitietdonhang;
    }
    
    public void setIdchitietdonhang(Integer idchitietdonhang) {
        this.idchitietdonhang = idchitietdonhang;
    }
    public int getIddonhang() {
        return this.iddonhang;
    }
    
    public void setIddonhang(int iddonhang) {
        this.iddonhang = iddonhang;
    }
    public double getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(double thanhTien) {
        this.thanhTien = thanhTien;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }
    public String getIdSanPham() {
        return this.idSanPham;
    }
    
    public void setIdSanPham(String idSanPham) {
        this.idSanPham = idSanPham;
    }




}


