package com.javaweb.model;
// Generated Dec 17, 2016 5:50:55 PM by Hibernate Tools 4.3.1



/**
 * Chitietdonhang generated by hbm2java
 */
public class Chitietdonhang  implements java.io.Serializable {


     private Integer idChiTietDonHang;
     private Donhang donhang;
     private Sanpham sanpham;
     private int soLuong;
     private double thanhTien;
     private String ghiChu;

    public Chitietdonhang() {
    }

    public Chitietdonhang(Donhang donhang, Sanpham sanpham, int soLuong, double thanhTien, String ghiChu) {
       this.donhang = donhang;
       this.sanpham = sanpham;
       this.soLuong = soLuong;
       this.thanhTien = thanhTien;
       this.ghiChu = ghiChu;
    }
   
    public Integer getIdChiTietDonHang() {
        return this.idChiTietDonHang;
    }
    
    public void setIdChiTietDonHang(Integer idChiTietDonHang) {
        this.idChiTietDonHang = idChiTietDonHang;
    }
    public Donhang getDonhang() {
        return this.donhang;
    }
    
    public void setDonhang(Donhang donhang) {
        this.donhang = donhang;
    }
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public double getThanhTien() {
        return this.thanhTien;
    }
    
    public void setThanhTien(double thanhTien) {
        this.thanhTien = thanhTien;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }




}


