package com.javaweb.model;
// Generated Dec 17, 2016 5:50:55 PM by Hibernate Tools 4.3.1



/**
 * Chitietdonhangla generated by hbm2java
 */
public class Chitietdonhangla  implements java.io.Serializable {


     private Integer idchitietdonhangla;
     private int iddonhangla;
     private int idsanpham;
     private int soluong;
     private double thanhtien;
     private Integer ghichu;

    public Chitietdonhangla() {
    }

	
    public Chitietdonhangla(int iddonhangla, int idsanpham, int soluong, double thanhtien) {
        this.iddonhangla = iddonhangla;
        this.idsanpham = idsanpham;
        this.soluong = soluong;
        this.thanhtien = thanhtien;
    }
    public Chitietdonhangla(int iddonhangla, int idsanpham, int soluong, double thanhtien, Integer ghichu) {
       this.iddonhangla = iddonhangla;
       this.idsanpham = idsanpham;
       this.soluong = soluong;
       this.thanhtien = thanhtien;
       this.ghichu = ghichu;
    }
   
    public Integer getIdchitietdonhangla() {
        return this.idchitietdonhangla;
    }
    
    public void setIdchitietdonhangla(Integer idchitietdonhangla) {
        this.idchitietdonhangla = idchitietdonhangla;
    }
    public int getIddonhangla() {
        return this.iddonhangla;
    }
    
    public void setIddonhangla(int iddonhangla) {
        this.iddonhangla = iddonhangla;
    }
    public int getIdsanpham() {
        return this.idsanpham;
    }
    
    public void setIdsanpham(int idsanpham) {
        this.idsanpham = idsanpham;
    }
    public int getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(int soluong) {
        this.soluong = soluong;
    }
    public double getThanhtien() {
        return this.thanhtien;
    }
    
    public void setThanhtien(double thanhtien) {
        this.thanhtien = thanhtien;
    }
    public Integer getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(Integer ghichu) {
        this.ghichu = ghichu;
    }




}


