package com.javaweb.model;
// Generated Nov 26, 2016 3:44:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Donhang generated by hbm2java
 */
public class Donhang  implements java.io.Serializable {


     private int iddonhang;
     private int iduser;
     private Date ngayTao;
     private double tongTien;

    public Donhang() {
    }

    public Donhang(int iddonhang, int iduser, Date ngayTao, double tongTien) {
       this.iddonhang = iddonhang;
       this.iduser = iduser;
       this.ngayTao = ngayTao;
       this.tongTien = tongTien;
    }
   
    public int getIddonhang() {
        return this.iddonhang;
    }
    
    public void setIddonhang(int iddonhang) {
        this.iddonhang = iddonhang;
    }
    public int getIduser() {
        return this.iduser;
    }
    
    public void setIduser(int iduser) {
        this.iduser = iduser;
    }
    public Date getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(Date ngayTao) {
        this.ngayTao = ngayTao;
    }
    public double getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(double tongTien) {
        this.tongTien = tongTien;
    }




}


