package com.javaweb.model;
// Generated Dec 15, 2016 1:23:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Loaisanpham generated by hbm2java
 */
public class Loaisanpham  implements java.io.Serializable {


     private Integer idLoaiSanPham;
     private String tenLoaiSanPham;
     private int idParent;
     private String moTa;
     private Set<Sanpham> sanphams = new HashSet<Sanpham>(0);

    public Loaisanpham() {
    }

	
    public Loaisanpham(String tenLoaiSanPham, int idParent) {
        this.tenLoaiSanPham = tenLoaiSanPham;
        this.idParent = idParent;
    }
    public Loaisanpham(String tenLoaiSanPham, int idParent, String moTa, Set<Sanpham> sanphams) {
       this.tenLoaiSanPham = tenLoaiSanPham;
       this.idParent = idParent;
       this.moTa = moTa;
       this.sanphams = sanphams;
    }
   
    public Integer getIdLoaiSanPham() {
        return this.idLoaiSanPham;
    }
    
    public void setIdLoaiSanPham(Integer idLoaiSanPham) {
        this.idLoaiSanPham = idLoaiSanPham;
    }
    public String getTenLoaiSanPham() {
        return this.tenLoaiSanPham;
    }
    
    public void setTenLoaiSanPham(String tenLoaiSanPham) {
        this.tenLoaiSanPham = tenLoaiSanPham;
    }
    public int getIdParent() {
        return this.idParent;
    }
    
    public void setIdParent(int idParent) {
        this.idParent = idParent;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }
    public Set<Sanpham> getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set<Sanpham> sanphams) {
        this.sanphams = sanphams;
    }




}


