package com.javaweb.model;
// Generated Nov 26, 2016 3:44:35 PM by Hibernate Tools 4.3.1



/**
 * Loaisanpham generated by hbm2java
 */
public class Loaisanpham  implements java.io.Serializable {


     private Integer idLoaiSanPham;
     private String tenLoaiSanPham;
     private int idparent;
     private String moTa;

    public Loaisanpham() {
    }

	
    public Loaisanpham(String tenLoaiSanPham, int idparent) {
        this.tenLoaiSanPham = tenLoaiSanPham;
        this.idparent = idparent;
    }
    public Loaisanpham(String tenLoaiSanPham, int idparent, String moTa) {
       this.tenLoaiSanPham = tenLoaiSanPham;
       this.idparent = idparent;
       this.moTa = moTa;
    }
   
    public Integer getIdLoaiSanPham() {
        return this.idLoaiSanPham;
    }
    
    public void setIdLoaiSanPham(Integer idLoaiSanPham) {
        this.idLoaiSanPham = idLoaiSanPham;
    }
    public String getTenLoaiSanPham() {
        return this.tenLoaiSanPham;
    }
    
    public void setTenLoaiSanPham(String tenLoaiSanPham) {
        this.tenLoaiSanPham = tenLoaiSanPham;
    }
    public int getIdparent() {
        return this.idparent;
    }
    
    public void setIdparent(int idparent) {
        this.idparent = idparent;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }




}


