package com.javaweb.model;
// Generated Nov 28, 2016 1:52:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Quyen generated by hbm2java
 */
public class Quyen  implements java.io.Serializable {


     private Integer idQuyen;
     private String tenQuyen;
     private String moTa;
     private Set<Users> userses = new HashSet<Users>(0);

    public Quyen() {
    }

	
    public Quyen(String tenQuyen, String moTa) {
        this.tenQuyen = tenQuyen;
        this.moTa = moTa;
    }
    public Quyen(String tenQuyen, String moTa, Set<Users> userses) {
       this.tenQuyen = tenQuyen;
       this.moTa = moTa;
       this.userses = userses;
    }
   
    public Integer getIdQuyen() {
        return this.idQuyen;
    }
    
    public void setIdQuyen(Integer idQuyen) {
        this.idQuyen = idQuyen;
    }
    public String getTenQuyen() {
        return this.tenQuyen;
    }
    
    public void setTenQuyen(String tenQuyen) {
        this.tenQuyen = tenQuyen;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


