package com.javaweb.model;
// Generated Nov 26, 2016 3:44:35 PM by Hibernate Tools 4.3.1



/**
 * Quyen generated by hbm2java
 */
public class Quyen  implements java.io.Serializable {


     private Integer idQuyen;
     private String tenQuyen;
     private String moTa;

    public Quyen() {
    }

    public Quyen(String tenQuyen, String moTa) {
       this.tenQuyen = tenQuyen;
       this.moTa = moTa;
    }
   
    public Integer getIdQuyen() {
        return this.idQuyen;
    }
    
    public void setIdQuyen(Integer idQuyen) {
        this.idQuyen = idQuyen;
    }
    public String getTenQuyen() {
        return this.tenQuyen;
    }
    
    public void setTenQuyen(String tenQuyen) {
        this.tenQuyen = tenQuyen;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }




}


