package com.javaweb.model;
// Generated Nov 26, 2016 3:44:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tintuc generated by hbm2java
 */
public class Tintuc  implements java.io.Serializable {


     private Integer idTinTuc;
     private int idLoaiTin;
     private String tieuDe;
     private String linkTin;
     private Date ngayDang;
     private String iduser;
     private String noiDung;
     private String tomTatTin;
     private String image;

    public Tintuc() {
    }

	
    public Tintuc(int idLoaiTin, String tieuDe, String iduser, String noiDung, String tomTatTin) {
        this.idLoaiTin = idLoaiTin;
        this.tieuDe = tieuDe;
        this.iduser = iduser;
        this.noiDung = noiDung;
        this.tomTatTin = tomTatTin;
    }
    public Tintuc(int idLoaiTin, String tieuDe, String linkTin, Date ngayDang, String iduser, String noiDung, String tomTatTin, String image) {
       this.idLoaiTin = idLoaiTin;
       this.tieuDe = tieuDe;
       this.linkTin = linkTin;
       this.ngayDang = ngayDang;
       this.iduser = iduser;
       this.noiDung = noiDung;
       this.tomTatTin = tomTatTin;
       this.image = image;
    }
   
    public Integer getIdTinTuc() {
        return this.idTinTuc;
    }
    
    public void setIdTinTuc(Integer idTinTuc) {
        this.idTinTuc = idTinTuc;
    }
    public int getIdLoaiTin() {
        return this.idLoaiTin;
    }
    
    public void setIdLoaiTin(int idLoaiTin) {
        this.idLoaiTin = idLoaiTin;
    }
    public String getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }
    public String getLinkTin() {
        return this.linkTin;
    }
    
    public void setLinkTin(String linkTin) {
        this.linkTin = linkTin;
    }
    public Date getNgayDang() {
        return this.ngayDang;
    }
    
    public void setNgayDang(Date ngayDang) {
        this.ngayDang = ngayDang;
    }
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }
    public String getTomTatTin() {
        return this.tomTatTin;
    }
    
    public void setTomTatTin(String tomTatTin) {
        this.tomTatTin = tomTatTin;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


